const styles = () => ({
    basic: {
      borderRadius: '50px',
      background: 'linear-gradient(to right, #43cea2, #185a9d)',
      width: '300px',
      height: '50px',
      boxShadow: '#AFC2C9 0px 5px 15px',
      color: '#fff',
      fontWeight: 'bold',
      letterSpacing: '1px',
      fontSize: '17px',
      borderRadius: '50px',
      height: '50px',
      borderRadius: '50px',
      marginBottom: '20px',
    },
    google: {
        borderRadius: '50px',
        backgroundColor: '#c33219',
        background: 'linear-gradient(to right, #e64522, #c33219)',
        width: '300px',
        height: '50px',
        boxShadow: '#AFC2C9 0px 5px 15px',
        color: '#fff',
        fontWeight: 'bold',
        letterSpacing: '1px',
        fontSize: '17px',
        borderRadius: '50px',
        height: '50px',
        borderRadius: '50px',
        marginBottom: '20px',
    },
    facebook: {
        borderRadius: '50px',
        backgroundColor: '#2b4170',
        background: 'linear-gradient(to right, #3b5998, #2b4170)',
        width: '300px',
        height: '50px',
        boxShadow: '#AFC2C9 0px 5px 15px',
        color: '#fff',
        fontWeight: 'bold',
        letterSpacing: '1px',
        fontSize: '17px',
        borderRadius: '50px',
        height: '50px',
        borderRadius: '50px',
        marginBottom: '20px',
    },
    twitter: {
        borderRadius: '50px',
        backgroundColor: '#0081ce',
        background: 'linear-gradient(to right, #00aced, #0081ce)',
        width: '300px',
        height: '50px',
        boxShadow: '#AFC2C9 0px 5px 15px',
        color: '#fff',
        fontWeight: 'bold',
        letterSpacing: '1px',
        fontSize: '17px',
        borderRadius: '50px',
        height: '50px',
        borderRadius: '50px',
        marginBottom: '20px',
    },
    instagram: {
        borderRadius: '50px',
        backgroundColor: '#f09433',
        background: 'linear-gradient(45deg, #f09433 0%,#e6683c 25%,#dc2743 50%,#cc2366 75%,#bc1888 100%)',
        width: '300px',
        height: '50px',
        boxShadow: '#AFC2C9 0px 5px 15px',
        color: '#fff',
        fontWeight: 'bold',
        letterSpacing: '1px',
        fontSize: '17px',
        borderRadius: '50px',
        height: '50px',
        borderRadius: '50px',
        marginBottom: '20px',
    }
  });

export default styles;