const styles = () => ({
    basic: {
      borderRadius: '50px',
      background: 'linear-gradient(to right, #43cea2, #185a9d)',
      width: '300px',
      height: '50px',
      boxShadow: '#AFC2C9 0px 5px 15px',
      color: '#fff',
      fontWeight: 'bold',
      letterSpacing: '1px',
      fontSize: '17px',
      borderRadius: '50px',
      height: '50px',
      borderRadius: '50px',
      marginBottom: '20px',
    },
    google: {
        borderRadius: '50px',
        background: 'linear-gradient(to right, #FF2900, #D50000)',
        width: '300px',
        height: '50px',
        boxShadow: '#AFC2C9 0px 5px 15px',
        color: '#fff',
        fontWeight: 'bold',
        letterSpacing: '1px',
        fontSize: '17px',
        borderRadius: '50px',
        height: '50px',
        borderRadius: '50px',
        marginBottom: '20px',
    },
    facebook: {
        borderRadius: '50px',
        background: 'linear-gradient(to right, #1A5FFA, #3F5EAD)',
        width: '300px',
        height: '50px',
        boxShadow: '#AFC2C9 0px 5px 15px',
        color: '#fff',
        fontWeight: 'bold',
        letterSpacing: '1px',
        fontSize: '17px',
        borderRadius: '50px',
        height: '50px',
        borderRadius: '50px',
        marginBottom: '20px',
    },
    twitter: {
        borderRadius: '50px',
        background: 'linear-gradient(to right, #3AA1F2, #2d87cc)',
        width: '300px',
        height: '50px',
        boxShadow: '#AFC2C9 0px 5px 15px',
        color: '#fff',
        fontWeight: 'bold',
        letterSpacing: '1px',
        fontSize: '17px',
        borderRadius: '50px',
        height: '50px',
        borderRadius: '50px',
        marginBottom: '20px',
    }
  });

export default styles;